find_path(SHENANGO_BASE_INCLUDE_DIR NAMES base)
mark_as_advanced(SHENANGO_BASE_INCLUDE_DIR)

find_library(SHENANGO_BASE_LIBRARY NAMES libbase.a)
mark_as_advanced(SHENANGO_BASE_LIBRARY)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  SHENANGO_BASE
  REQUIRED_VARS SHENANGO_BASE_LIBRARY SHENANGO_BASE_INCLUDE_DIR
)

if(SHENANGO_BASE_FOUND)
  set(SHENANGO_BASE_LIBRARIES ${SHENANGO_BASE_LIBRARY})
  set(SHENANGO_BASE_INCLUDE_DIRS ${SHENANGO_BASE_INCLUDE_DIR})
  message(STATUS "Found Shenango Base: ${SHENANGO_BASE_LIBRARY}")
endif()
