find_path(SHENANGO_INCLUDE_DIR NAMES runtime.h)
mark_as_advanced(SHENANGO_INCLUDE_DIR)

find_library(SHENANGO_LIBRARY NAMES librt++.a)
mark_as_advanced(SHENANGO_LIBRARY)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  SHENANGO
  REQUIRED_VARS SHENANGO_LIBRARY SHENANGO_INCLUDE_DIR
)

if(SHENANGO_FOUND)
  set(SHENANGO_LIBRARIES ${SHENANGO_LIBRARY})
  set(SHENANGO_INCLUDE_DIRS ${SHENANGO_INCLUDE_DIR})
  message(STATUS "Found Shenango: ${SHENANGO_LIBRARY}")
endif()
