find_path(SHENANGO_RUNTIME_INCLUDE_DIR NAMES runtime.h)
mark_as_advanced(SHENANGO_RUNTIME_INCLUDE_DIR)

find_library(SHENANGO_RUNTIME_LIBRARY NAMES librt++.a)
mark_as_advanced(SHENANGO_RUNTIME_LIBRARY)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  SHENANGO_RUNTIME
  REQUIRED_VARS SHENANGO_RUNTIME_LIBRARY SHENANGO_RUNTIME_INCLUDE_DIR
)

if(SHENANGO_RUNTIME_FOUND)
  set(SHENANGO_RUNTIME_LIBRARIES ${SHENANGO_RUNTIME_LIBRARY})
  set(SHENANGO_RUNTIME_INCLUDE_DIRS ${SHENANGO_RUNTIME_INCLUDE_DIR})
  message(STATUS "Found Shenango Runtime: ${SHENANGO_RUNTIME_LIBRARY}")
endif()
